### ISSUE TITLE
Error running patch_cluster.py

### ISSUE THREAD

**Issue by lixiaolulixiaolu** [stanford-mast/pocket#10]
I'm trying to deploy Pocket in aws following deploy/README.md. And I successfully install the kubernetes cluster in aws. However, when I run `$> python patch_cluster.py`, the following error occurs:

```bash
Traceback (most recent call last):
  File "patch_cluster.py", line 213, in <module>
    main()
  File "patch_cluster.py", line 205, in main
    add_lambda_security_group_ingress_rule()
  File "patch_cluster.py", line 189, in add_lambda_security_group_ingress_rule
    pocket_lax_groupid = re.search(pattern, out).group().strip('\"')
AttributeError: 'NoneType' object has no attribute 'group'
```
The function `add_lambda_security_group_ingress_rule` tries to find the groupid for a security group,
whose name is in the format of `*pocket-kube-relax*`. I check the security groups in my account and there are no such security groups. I wonder whether we need to create one by ourselves and configure it for lambda functions later on?

**Comment by anakli** [comment]
Yes, you need to create a security group for your Pocket VMs and the lambdas that will connect to Pocket. The `patch_cluster.py` script assumes your security group is called "pocket-kube-relax", but feel free to edit the script to match your security group name.
