### ISSUE TITLE
Custom VPC Configuration for Pocket

### ISSUE THREAD

**Issue by devloop0** [stanford-mast/pocket#13]
I've got pocket working with the configuration given in README.md in the deploy/ folder.

However, I would like to be able to access pocket from a separate EKS cluster (so in a completely different VPC with its own subnets/security groups/etc.). As of now, I'm able to access pocket from an AWS lambda, but I'm unable to access it from any of the worker nodes in the EKS cluster. I've already tried setting up a peering connection, but that does seem to help.

- Would it be possible to deploy pocket in an already existing VPC?
- Are the public/private subnets necessary to the functionality of pocket?
- Is cross-VPC communication possible in pocket, or does everything need to be in the same VPC?

**Comment by anakli** [comment]
Yes, you can deploy Pocket in an already existing VPC. Just make sure to put the name of your existing VPC, security groups, etc. in the [env.sh](https://github.com/stanford-mast/pocket/blob/master/deploy/env.sh) file and source it.

According to the [Amazon documentation](https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html), enabling lambdas to access both VPC and public internet services requires using a NAT and private subnets. This is why we create a VPC setup for Pocket like in [this example scenario](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html) described in the Amazon docs. If you would like to use Pocket for jobs that run on EC2 machines or for lambdas that only need to access the Pocket VPC and no public internet services (such as S3), it should be fine to use a simpler setup with just a public subnet and no NAT. However, we have not tested this.

Pocket itself does not impose restrictions on communication being in a single VPC, however I am not familiar with what AWS currently supports when it comes to cross-VPC communication. You might find [this](https://aws.amazon.com/answers/networking/aws-single-region-multi-vpc-connectivity/) link helpful.
