### ISSUE TITLE
kubernetes deploy issue

### ISSUE THREAD

**Issue by photoszzt** [stanford-mast/pocket#2]
I'm creating the vpc using the create_pocket_vpc.sh and setup the cluster as the readme said. When I run `kops validate cluster`, I get the following error:

```
Using cluster from kubectl context: pocketcluster.k8s.local

Validating cluster pocketcluster.k8s.local


unexpected error during validation: error listing nodes: Get https://internal-api-pocketcluster-k8s-loc-404v42-1135504292.us-west-2.elb.amazonaws.com/api/v1/nodes: dial tcp 10.1.65.233:443: connect: no route to host
```
I have waited for half an hour. All the ec2 machine are up and running from the dashboard.

**Comment by anakli** [comment]
Can you try setting up the VPC with the AWS VPC wizard instead of the create_pocket_vpc.sh script and see if this helps?

**Comment by photoszzt** [comment]
@anakli Unfortunately, that also doesn't work. I haven't found a way to make kops work with vpc.

**Comment by photoszzt** [comment]
Never mind, finally figure out.

**Comment by jananiej** [comment]
@photoszzt  Can you explain the way you've figured out as I'm also having the same issue.
Thank you

**Comment by photoszzt** [comment]
@jananiej You can start from this scripts: https://github.com/photoszzt/k8s-aws You need to modify the cluster definition to what pocket expects. To save money, I use the free tier to start the nodes. The pocket's configuration costs me a lot when I'm experimenting with the setup.

**Comment by photoszzt** [comment]
@jananiej The cluster config generates three master nodes. To change that, you need to remove two azs in main.tf to only one and change the region to us-west-2c. You also need to change some worker node's image to ami-...(I forget the exact number, you should be able to find it in pocket's cluster definition yaml file).
