### ISSUE TITLE
Error with validating cluster

### ISSUE THREAD

**Issue by devloop0** [stanford-mast/pocket#7]
Hi,

I'm trying to set up Pocket with the directions in the `README.md` file in the `deploy/` folder, but I seem to be running into the issue where `kops validate cluster` is hanging (even after waiting for up to an hour).
I first ran `./create_pocket_vpc.sh` from a VM and then created a VM with an IP of `10.1.47.178` inside of the `pocket-kube-private` subnet (I later also tried manually creating a VPC as well, but this didn't work either).
Then, I followed the instructions up to the point of `./setup_cluster.sh`. If I run `kops validate cluster`, I get the following error:
`unexpected error during validation: error listing nodes: Get https://internal-api-pocketcluster-k8s-loc-404v42-977648002.us-west-2.elb.amazonaws.com/api/v1/nodes: EOF`
(Something similar happens if I try to run `kubectl get nodes` as well).
If I run `kops validate cluster -v 10`, I seem to get that error while requesting the following:
`I1104 01:15:16.994615   31176 request_logger.go:45] AWS request: ec2/DescribeAvailabilityZones`
Not exactly sure why this is happening, since I'm using an access key id and secret id that has full permissions for my account. Any ideas what could be causing the problem?

Thanks!

**Comment by anakli** [comment]
Looks like the API Gateway is not properly set up. Can you check if the issue is related to the one in [this](https://github.com/stanford-mast/pocket/issues/1#issuecomment-445398885) thread?

**Comment by devloop0** [comment]
Thanks!

I looked at the instructions [here](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-testing) and it seems like I'm able to `ping ietf.org` and running `traceroute ietf.org` also seems to show the private IP of the NAT as the first hop. Additionally, the route tables seem to match what is shown [here](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html#VPC_Scenario2_Routing).
Are there any other things that could cause this issue?

**Comment by devloop0** [comment]
Resolved. I manually created the vpc, subnets, etc.
However, I also needed lower versions of kubectl and kops.

**Comment by obrr-hhx** [comment]
@devloop0 Hello, I also have met the same EOF error, can you tell me which the version of kops and kubectl you use? I think it will be very helpful, thanks.
